### ISSUE TITLE
0.5.0 is broken

### ISSUE THREAD

**Issue by mvdstam** [mikeerickson/gulp-phpspec#8]
```js
// index.js:56

var cmd      = '';
```

Should be:

```js
// index.js:56

var cmd      = command;
```

With the newest version, nothing is being executed at all regarding tests. Please check your other gulp-* packages that have been refactored in the same manner as well, since they are probably broken as well now.

**Comment by mikeerickson** [comment]
Interesting, it is working fine here?  I will have a closer look and see what I can find.  

Can you please send me a copy of the task you have created?

**Comment by mikeerickson** [comment]
@mvdstam OK, figured out the issue (internal copy/paste issue).

New version 0.5.3 contains the fix.
