### ISSUE TITLE
opt.clear=true doesn't work for Windows.

### ISSUE THREAD

**Issue by thefuzzy0ne** [mikeerickson/gulp-phpspec#9]
When I pass this option in, I receive the following error:

'clear' is not recognized as an internal or external command, operable program or batch file.

This is Windows' standard response when you try to run a command that doesn't exist. On windows machines, the command to clear the console screen is 'cls'. I know, I know - it's silly... But is there any way you can fix this so that it so that this works on Windows?

I would give it a bash, but my Git knowledge is mucho rusty.

Many thanks in advance.

**Comment by mikeerickson** [comment]
Sure thing, I will adjust it internally for you :)

**Comment by thefuzzy0ne** [comment]
Many thanks. :)

**Comment by mikeerickson** [comment]
I will get this added over the weekend and post a new version.  I do have a few other things to add so I will get it all done weekend

**Comment by mikeerickson** [comment]
@thefuzzy0ne OK, this has been cured

You can get latest here

```
$ npm i -D gulp-phpspec@latest
```

**Comment by thefuzzy0ne** [comment]
Many thanks for this, Mike. :)
